# Generated by Django 4.2.5 on 2023-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('quota', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='courses.course')),
            ],
        ),
    ]
