# Generated by Django 4.2.5 on 2023-10-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
